name: 🚀 Feature request
description: Suggest an idea for this project
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make LibDriver better.

        Please fill in as much of the following form as you're able.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the idea you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.